fix: tight controlbar coupling (#7689)
videojs/video.js pull request #7692
Opened 2022-03-24 10:20 UTC by try2beth3b3st

## Description
We have tight coupling in player.js Class Player method resetControlBarUI_(), when using reset() method.
ControlBar component may be not exists or exists on another nesting level..

## Specific Changes proposed
Added condition

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

2022-03-25 10:27 UTC, try2beth3b3st commented
> Nice, these missing null checks are too common! Would you mind adding a test for this case?

Done..

2022-03-28 14:46 UTC, misteroneill requested changes
One minor quibble, otherwise looks good!

2022-03-28 14:46 UTC, misteroneill commented on test/unit/player.test.js
> +  player.removeChild('controlBar');
This is a reasonable test, but the `player.controlBar` property appears to still exist even when `removeChild` is called.

```suggestion
  player.removeChild('controlBar');
  player.controlBar = null;
```

2022-03-29 15:33 UTC, gkatsev approved these changes

2022-05-04 12:50 UTC, try2beth3b3st commented
@misteroneill Excuse me, when to expect patch with this fix?)

2022-05-04 15:43 UTC, merged