feat: remove use of firstplay event
videojs/video.js pull request #7707
Opened 2022-04-05 14:42 UTC by hugorogz

## Description
Removed the use of existing 'firstplay' events as it's deprecated in: https://github.com/videojs/video.js/pull/4353

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

2022-04-05 16:20 UTC, mister-ben requested changes
We wouldn't need to trigger `play` instead of `firstplay` -- `play` is already fired so we'll end up with duplicate events.

2022-04-05 20:25 UTC, mister-ben commented on src/js/player.js
>       * @deprecated As of 6.0 firstplay event is deprecated.
This and other comments relating to `firstplay` can be removed now too.

2022-04-06 14:58 UTC, gkatsev requested changes

2022-04-06 14:58 UTC, gkatsev commented on docs/legacy-docs/api/js/doc-data-full.js
> -    {
this piece should stay as it relates to legacy docs.

2022-04-07 15:36 UTC, misteroneill approved these changes
Looking good to me!

2022-04-08 08:38 UTC, mister-ben approved these changes

2022-04-19 16:34 UTC, amtins commented
Just for my understanding, I see that this PR has the **major** label. Does this mean that the `firstplay` event will be removed in version 8?

2022-04-19 17:49 UTC, mister-ben commented
That's right

2022-05-16 21:24 UTC, merged