feat(lang): Add Bengali (bn) translations
videojs/video.js pull request #7823
Opened 2022-06-30 13:17 UTC by themaruf

## Description
Add completed translations for Bengali language.

## Specific Changes proposed
New file of Bengali (bn.json) language strings.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

2022-07-04 09:54 UTC, mister-ben commented on lang/bn.json
> +    "progress bar timing: currentTime={1} duration={2}": "{২} এর {১}",
These tokens need to remains as exactly `{1}` and `{2}` for the replacement to work.

2022-07-04 09:54 UTC, mister-ben commented on lang/bn.json
> +    "{1} is loading.": "{১} লোড হচ্ছে.",
```suggestion
    "{1} is loading.": "{1} লোড হচ্ছে.",
```

2022-07-04 09:58 UTC, mister-ben requested changes
See comments about the replacement tokens, otherise looks good.

2022-07-05 14:46 UTC, mister-ben commented on lang/bn.json
> +    "progress bar timing: currentTime={1} duration={2}": "{২} এর {১}",
Like this:

```suggestion
    "progress bar timing: currentTime={1} duration={2}": "{2} এর {1}",
```

2022-08-02 16:38 UTC, misteroneill approved these changes
LGTM, thank you for the PR!

2022-08-04 11:58 UTC, mister-ben approved these changes

2022-09-15 15:15 UTC, merged