fix(control-bar): align center
videojs/video.js pull request #7990
Opened 2022-11-03 05:55 UTC by KangXinzhi

## Description
[Please describe the change as necessary.
The bar is not centered in video control section
[issues7989](https://github.com/videojs/video.js/issues/7989)

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chrome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

2022-11-03 08:14 UTC, mister-ben requested changes
This causes the opposite issue for me: the handle is too high. There's been a few reports of this before #7004 which users have fixed with some CSS. It seems specific to Chinese OS/page. I wonder if there's something different about font rendering with Chinese characters which affects em units.

2022-11-03 08:27 UTC, KangXinzhi commented
> too high. There's been a few reports of th

When I open the videoJS official website, I have the same problem.  and it has not any Chinese.


<img width="1217" alt="image" src="https://user-images.githubusercontent.com/50164727/199674914-456a0cb9-1b05-4eb8-befa-0fd22654e76f.png">

2022-11-03 19:29 UTC, mister-ben commented
I can replicate what you see if I run Chrome in Chinese Traditional on MacOS - the application rather than the page language is apparently what matters. I note the handle is slightly larger.

Removing those two `top` rules and replacing them with `line-height: .35em;` seems to work well with the browser in English, Chinese, Arabic, Hindi, Japanese on Mac Chrome, Safari, Firefox and Edge. Would need some testing on Windows - if it works there two, it looks like a solution. It should be merged into `next` rather than `main` - it could be a breaking change for custom styles.

2022-11-04 18:16 UTC, mister-ben commented
In this codepen, the first player uses the styling we currently have, and the second uses `line-height` instead of `top`. On all MacOS browsrs I've tried, the slider handles are in the correct place regarless of OS/app language for the second player.

I haven't tried on Windows as the standard edition of Windows doesn't let you change the OS/app language. If @KangXinzhi  or anyone else could try this on Chinese (or other non-Latin script) Windows browsers it would be useful.

https://codepen.io/mister-ben/full/MWXeOKr

2022-11-05 16:05 UTC, KangXinzhi commented
> 
It is great when I try this on Chinese Windows browsers！
![image](https://user-images.githubusercontent.com/50164727/200129030-cae5a582-651b-4f77-9718-2ca9d812317d.png)

![image](https://user-images.githubusercontent.com/50164727/200129040-ce5bc06e-2b17-490b-b014-cb55f20605f5.png)

2022-11-06 09:30 UTC, mister-ben commented on src/css/components/_progress.scss
> +
```suggestion
```

2022-11-06 09:31 UTC, mister-ben commented on src/css/components/_progress.scss
> +    top: -0.45em;
```suggestion
    line-height: .35em;
    z-index: 1;
```

2022-11-06 09:31 UTC, mister-ben commented on src/css/components/_volume.scss
> +    top: -0.45em;
```suggestion
    line-height: .35em;
```

2022-11-06 09:35 UTC, mister-ben requested changes
These suggested changes are as my codpen example.

2022-11-07 16:05 UTC, mister-ben commented
This could be a breaking change for custom skins, so should be in a major release - v8.x should be very soon now. Could you rebase agains the next branch?

2022-11-08 02:53 UTC, KangXinzhi commented
> This could be a breaking change for custom skins, so should be in a major release - v8.x should be very soon now. Could you rebase agains the next branch?

that's ok!

2022-11-08 07:56 UTC, mister-ben approved these changes

2022-11-08 14:15 UTC, misteroneill approved these changes
Took a quick look and seems to work nicely. Thank you @KangXinzhi!

2022-11-08 14:18 UTC, merged